### PR TITLE
Added `enchantment`, `shatteredglass`, `upsidedowndfc` frame effects

### PR DESCRIPTION
**Pull request by missingems**
Added some of the missing frame effects https://scryfall.com/docs/api/frames

### CODE REVIEW

**Comment by missingems** [comment]
@JacobHearst

**Comment by JacobHearst** [comment]
Thanks @missingems! I saw the alerts about the failed builds but haven't had time to actually get around to fixing them. I've been considering for a while whether these frequently updated enums even need to exist or if they should just be strings, do you have any opinion on this?

**Comment by missingems** [comment]
> Thanks @missingems! I saw the alerts about the failed builds but haven't had time to actually get around to fixing them. I've been considering for a while whether these frequently updated enums even need to exist or if they should just be strings, do you have any opinion on this?

I personally think we can keep the enum as it is and update it occasionally. The cycle from WotC is also fairly predictable. Personally, I rely on the different frame effects to render various types of shaders. Removing the enum would mean we’d have to switch to using strings instead, which shifts the responsibility of ensuring each frame effect value is correct onto the implementer.

I can also help contribute more often if things becoming too hectic from Wotc (hopefully not).

**Comment by JacobHearst** [comment]
Sounds good to me, I'll get this merged and released!

**Pull request merged**
